// FIX: Implemented a basic MarkdownRenderer component to format and display text content generated by the Gemini API. It handles bold headings and bullet points as specified in the service prompts, resolving the error from the placeholder file.
import React from 'react';

interface MarkdownRendererProps {
  content: string;
}

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ content }) => {
  const renderContent = () => {
    if (!content) return null;

    const lines = content.split('\n');
    const elements = [];
    let listItems = [];

    const flushList = () => {
      if (listItems.length > 0) {
        elements.push(<ul key={`ul-${elements.length}`} className="list-disc pl-5 space-y-1 my-2">{listItems}</ul>);
        listItems = [];
      }
    };

    lines.forEach((line, index) => {
      // Bold headings: **Heading**
      if (line.startsWith('**') && line.endsWith('**')) {
        flushList();
        elements.push(<h3 key={index} className="text-lg font-bold mt-4 mb-2 text-slate-800 dark:text-slate-100">{line.substring(2, line.length - 2)}</h3>);
        return;
      }

      // Bullet points: * Item
      if (line.trim().startsWith('* ')) {
        listItems.push(<li key={index}>{line.trim().substring(2)}</li>);
        return;
      }
      
      flushList();
      
      // Normal paragraph
      if (line.trim() === '') {
        elements.push(<br key={index} />);
      } else {
        elements.push(<p key={index} className="my-2">{line}</p>);
      }
    });

    flushList(); // Add any remaining list items
    return elements;
  };

  return <div className="prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-300">{renderContent()}</div>;
};
